### ISSUE TITLE
data_managers should not use merge() solely based on existing in session or not.

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#100]
The current code at https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/data/data_managers.py#L105
for saving an object contains
```
if obj not in self.session:
    self.session.add(obj)
else:
    obj = self.session.merge(obj)
```
It is however possible that objects do exist in the session but are new as well.
All you need is a relationship between 2 objects, 1 already existing in the DB, the other is new.
For example. A Bijlage has BijlageTypes.
The types are predefined in the database, so when creating a new Bijlage you would link it to an existing type.

Simple code like this would create duplicate Bijlages:
```
bijlage_type = session.query(BijlageType).first()
# the session now contains:
# BijlageType instance: id=xx, ...

bijlage = Bijlage()
bijlage.types.add(bijlage_type)
# the session now contains:
# BijlageType instance: id=xx, ...
# Bijlage instance: id=None, ...

bijlage_data_manager.save(bijlage) 
# the session now contains:
# BijlageType instace: id=xx, ...
# Bijlage instance: id=None, ...
# Bijlage instance: id=None, ...
```
The duplicate Bijlage is added by sqlalchemy because `.merge()` relies on the primary key to find matching objectst. But because this is a new object with `id=None` this does not work. So sqlalchemy treats it like a new object.

Eventually flushing this session will create a duplicate Bijlage in the database. 

The `.merge()` block in the code needs to be evaluated.
Maybe it can be removed? sqlalchemy's `session.add()` has an internal `save_or_update`.
If not, the if-statement has to be made smarter by checking at the primary key to avoid these situations.

**Comment by claeyswo** [comment]
This has pretty big implications for all our applications.

Seeing this commit you are not the first to raise this issue: https://github.com/OnroerendErfgoed/oe_utils/commit/b1d5a6d5c2cdff497a1b9edec2a6d11b8d2508ac

Do you have any idea why this hasn't caused any problems before? Seems to me we should have run into this before.

**Comment by Wim-De-Clercq** [comment]
I assume because most of the time, when creating a new object with a foreign key you'd just set the id, and not really set it by linking the actual objects.

```
wheel = Wheel()
wheel.car_id = x
```
session hasn't been involved here yet
even if the car_id was validated before, the car would be in the session, but the car instance in the session has no knowledge of the wheel.
So a `datamanager.save()` invocation would do
```
if obj not in self.session:
    self.session.add(obj)
```
And that'll work fine. I suppose this way is how the majority of the code creates objects with foreign keys.

With many-to-many relationships however you can't really set the `_id`s like that because there's an association table. So either you use objects (like the bug). Or you manually create the association object like:
```
bijlage = Bijlage()
... # no link with type
data_manager.save(bijlage)

bijlage_bijlagetype = BijlageBijlagetype()
bijlage_bijlagetype.bijlage_id = bijlage.id
bijlage_bijlagetype.type_id = type.id
data_manager.save(bijlage_bijlagetype)
```
I don't think with a creation like this you won't have duplicates either, and the objects will still be linked properly.
But imo, this is a less nice way of creating that.

**Comment by Wim-De-Clercq** [comment]
Update:
It looks like this actually won't happen with `autoflush=True` which is the default. - I had it to false in my tests and that makes it visible.

**Comment by Wim-De-Clercq** [comment]
I wonder if I should close it now. There's just a limitation of requiring `autoflush=True` on the session. But all applications use this anyway.

I turned it on because in my test case i was doing
```
bijlage(aanvraag=None, types=[type_from_db])
aanvraag(bijlagen=[bijlage])
save(aanvraag)
```
And it would crash on the create bijlage because aanvraag_id is a not null column.
But I just have to reorder the steps in this case, creating aanvraag first, then adding bijlage.

**Comment by claeyswo** [comment]
It seems the merge is necessary though when updating an existing resource. The way we handle that now (I think):

- create a SQLAlchemy object based on the json received
- merge this with the existing state, doing an add here would result in duplicate primary keys?

Or we should change this to:

- load the existing SQLAlchemy object based on the id in the json received
- add will have no effect here so should work fine

So assuming the above is correct, implementing this change would require a rewrite of most our applications.

**Comment by Wim-De-Clercq** [comment]
Correct, the `merge` can't be removed.
I tested what happens if you `.add` an "self-made" object with a primary key filled in.

- If it didn't exist yet in the session --> Database error raised for duplicate primary key
- If it already existed in a session, and you `.add()` a self-made object, it will try to add again (because for sqlalchemy's `save_or_update` to trigger nicely it needs a `model._sa_instance_state.key` value which of course the selfmade object won't have. --> Database error raised for duplicate primary key
- if the object was previously fetched, then detached from session, then added again (while the same DB object is in the  session from another operation) --> "Can't attach instance X another instance with key Y is already present in this session."

So yes, the `merge` is definitely needed.

All that's left is the very specific case where a new object should be saved AND it's linked with an existing object AND it has no primary key yet (This requires `autoflush=False`). Then, and only then it should not merge.

**Comment by claeyswo** [comment]
So we keep it as is and make sure autoflush is set to True?

**Comment by Wim-De-Clercq** [comment]
Sounds good. We could add a simple check to the datamanager class' `__init__`.
```
def __init__(self, session, cls):
```
autoflush is a property of the session.

Should that log  warning or raise?

**Comment by claeyswo** [comment]
While we're at it, might as well fix this. I would raise on autoflush=false.
