### ISSUE TITLE
Het is best practice om functools.wraps te gebruiken bij decorators.

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#101]
Al de decorators die `oe_utils` aanbiedt zouden zelf een extra decorator moeten krijgen:
generiek voorbeeld:
```
import functools

def decorator(fn):
    @functools.wraps(fn)  # <<<<<----------
    def wrapped(*args, **kwargs):
        return fn(*args, **kwargs)
    return wrapped
```

Momenteel komt volgende code vrij veel voor (inventaris voorbeeld):
```
@aanduidingsobjecten_route.post
def add_aanduidingsobject(request):
    """Aanmaken van aanduidingsobject"""
    return _add_aanduidingsobject(request)


@audit_with_request(actie='aanduidingsobject aanmaken')
def _add_aanduidingsobject(request): # separate function because of summary extraction
```
En de reden dat er een tweede methode wordt aangemaakt is speciaal voor de audit decorator.

Omdat de audit decorator de `functools.wraps` niet gebruikt. Zal de api doc "Aanmaken van aanduidingsobject" verloren geraken, en deze wordt normaal door swagger gebruikt voor documentatie.

De `audit_with_request` decorator kan perfect samenwerken met swagger en andere decorators als ze geupdate wordt met `wraps`

```
def audit_with_request(**kwargs):
    """
    use this decorator to audit an operation with a request as input variable
    """
    def wrap(fn):
        @audit(**kwargs)
        def operation(parent_object, *args, **kw):
            return fn(parent_object.request, *args, **kw)

        @functools.wraps(fn)
        def advice_with_request(the_request, *args, **kw):
            class ParentObject:
                request = the_request

            return operation(ParentObject(), *args, **kw)

        return advice_with_request

    return wrap
```

En idem in feite voor al de decorators overal die geschreven worden. Ook al is er nog geen issue.Het is best practice om functools.wraps te gebruiken.

Zoals bvb bij dit voorbeeld
```
def decorator(fn):
    def wrapped(*args, **kwargs):
        return fn(*args, **kwargs)
    return wrapped


@decorator
def my_method():
    pass


print(my_method.__name__)
```
Je zou verwachten dat de naam `my_method` is, maar het is `wrapped`. Dit is wat `functools.wraps` corrigeert met nog meer metadata zoals de `__doc__`, parameter names etc...

**Comment by claeyswo** [comment]
@Wim-De-Clercq: Kan jij hier zelf een estimate op plakken?
