### ISSUE TITLE
Lege indexeringstaken mogen niet op de queue komen

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_utils#104]
Via https://github.com/OnroerendErfgoed/inventaris/issues/954#issuecomment-441014195 kwam naar boven dat er heel wat taken op de redis queue kwamen die eigenlijk lege lijsten bevatten.

Alvorens de job wordt toegevoegd moet worden nagegaan of 1 van de index_new, index_dirty of index_delete lijsten waarden bevatten

**Comment by claeyswo** [comment]
Lijkt mij niet al te groot, dan kan 0.27.0 de deur uit.
