### ISSUE TITLE
De audit decorator zou de pyramid json renderer kunnen gebruiken

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#106]
Deze lijn https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/audit.py#L66 : 
```
result_object_json = json.loads(dumps(jsonsettings(result, request=request)))
```
Zet een database object (`result`) om in json. Deze json wordt dan later opgeslagen in de database als een revision.

Om dit te doen werken werd `jsonpublish` gebruikt. Het gevolg van dit, is dat al de json renderers bij alle projecten met audit (de meeste) ook jsonpublish configuratie moeten hebben. 

bvb bij inventaris is een renderer file als volgt:
```
...
from jsonpublish import register_adapter
...
from inventaris.renderers.rest_renderer.common import json_renderer
...
@register_adapter(ErfgoedobjectOmvang)
def erfgoedobject_omvang_adapter(obj, request=None):
...
json_renderer.add_adapter(ErfgoedobjectOmvang, erfgoedobject_omvang_adapter)
...
```
Er wordt zowel `@register_adapter` gebruikt als `add_adapter` omdat er twee JSON renderers zijn. Er is die van pyramid, en er is de jsonpublish van de audit decorator.

Dit is niet goed omdat:

1. Dit is extra (dubbele) code
2. De adapters moeten allemaal rekening houden dan request None kan zijn, omdat de jsonpublish renderer eigenlijk niet deftig werkt (of misschien wel, maar niet op de manier zoals de audit decorator het doet). _- De request zal er zijn bij het root object dat wordt omgezet naar een dict, maar al de child objects die via de adapters worden opgeroepen zullen geen request krijgen._

----
Ik stel voor om in de audit decorator gewoon de pyramid renderer op te roepen. De code verwacht al een request object en oe_utils heeft pyramid in de `requirements.txt`, dus die import van pyramid lijkt mij niet erg.
```
from pyramid import renderer
...
result_object_json = json.loads(renderer.render('jsonrenderer', result, request=request))
```
De enige moeilijkheid is dat de audit decorator dan de naam van de renderer moet weten, maar dit kunnen we via setting files regelen of eventueel via parameters bij de `@audit` decorator.

Hierna kunnen al de projecten de jsonpublish weg gooien, hun renderers opkuisen, en alle rendering code zal altijd een request object krijgen.

**Comment by goessebr** [comment]
De jsonpublish is al langer een problematisch library door het gebrek aan onderhoud. Bepaalde packages kunnen niet meer worden geupgraded omwille van jsonpublish (https://github.com/OnroerendErfgoed/openbare_onderzoeken/pull/493). 
Gerelateerd aan dit issue is https://github.com/OnroerendErfgoed/openbare_onderzoeken/issues/434 ook het bekijken waard. 

Ik sta sterk achter dit voorstel
