### ISSUE TITLE
Rangeparser does not allow setting max

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/oe_utils#11]
In besluiten there's an older version that allows configuring the max nr of records returned at one time, in oe_utils this is hardcoded to 50.

**Comment by bdkock-geosolutions** [comment]
Be aware that due to the hard-coded value of 50 currently the max number of records returned per request is actually 51.

**Comment by BartSaelen** [comment]
put the max value as a configurable setting, if the settings is absent, do not limit, otherwise use the setting
