### ISSUE TITLE
Conformeren aan de Generieke Hypermedia API, bouwblok Paginering

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_utils#110]
Voor de volledige uitleg zie https://github.com/OnroerendErfgoed/beeldbank/issues/653

Hetgeen er denk ik zou moeten gebeuren:

- https://github.com/OnroerendErfgoed/oe_utils/blob/41311491c049b59abd9df35a23a1328d6d39f9b1/oe_utils/range_parser.py#L61
Naam van de parameter uit de settings proberen halen, default blijft het pagina. Parameter toevoegen, naam ook uit de settings, default per_pagina, die het aantal items bepaalt. Volstaat om default_end=per_pagina-1 te zetten?
- https://github.com/OnroerendErfgoed/oe_utils/blob/41311491c049b59abd9df35a23a1328d6d39f9b1/oe_utils/range_parser.py#L36
In gans dat stuk worden default 12 items opgehaald, lijkt beter om dit op iets te zetten als 10. Zou niets bestaand mogen breken denk ik?
- https://github.com/OnroerendErfgoed/oe_utils/blob/41311491c049b59abd9df35a23a1328d6d39f9b1/oe_utils/range_parser.py#L69
Link header meesturen in antwoorden: waarden voor next last, first en previous kunnen in principe allemaal berekend worden op basis van total_count, end en start. In url's zowel pagina meegeven als per_pagina (of hoe die parameters ook noemen in de settings), in tegenstelling tot voorbeeld in beeldbank#653.

**Comment by claeyswo** [comment]
@koenedaele:

Probleem dat ik hier nog zie is bij het opsturen van Ranges die niet kunnen vertaald worden naar paginanummers. Als ik bvb. 10-19 vraag is er geen probleem, per_page = end-start+1 dus in dit geval 10, current_page=end+1/per_page dus pagina 2.

Als ik echter iets opgeef als 10-60, dan is per_page 51 en bevinden we ons op pagina ~1.2. Wat doen we in dit geval?

- verbieden we Ranges die aanleiding geven tot decimale paginanummers?
- we sturen in dit geval geen Link header terug

Ik vraag mij trouwens af of het zin heeft die Link header terug te sturen als er een Range wordt gevraagd. Het doel lijkt mij te zijn om een client die een bepaalde pagina opvraagt te kunnen sturen naar de volgende/vorige/... pagina's. Een client die Range headers gebruikt heeft hier gewoon geen boodschap aan.

**Comment by koenedaele** [comment]
Op zich is het doel inderdaad hypermedia API's. Die gaan denk ik niet werken met range headers. Dus het is een optie om het weg te laten indien er met ranges gewerkt wordt. Enige dat we dan wel moeten doen is  in onze API docs duidelijk maken dat REST clients ook met pagina en per_pagina kunnen werken.

Dus, ok voor mij om de header niet te zetten als er met ranges gewerkt wordt.

Ik ga er van uit dat we niet toestaan dat per_pagina > max_end

**Comment by Wim-De-Clercq** [comment]
> Ik ga er van uit dat we niet toestaan dat per_pagina > max_end

Het zou in theorie mogelijk zijn als er in de code een lage max_end wordt gezet en er dan met de pagina queryparam wordt gewerkt. Bij de pagina code wordt niet gekeken naar max_end. In de praktijk komt dit niet voor geloof ik.

max_end heeft btw een beetje een ongelukkige naam omdat de end die je meegeeft in je range groter kan zijn dan max_end. Eigenlijk is max_end de "max_per_page - 1" ofzoiets. Ik zal het wel laten staan voor backwards compatibility.

----

Anyway, de reden van de comment: Bij ..
```
def set_response_headers(self, response, total_count): 
```
...ga ik het request object aan moeten toevoegen. Ik heb het request object nodig om een paar redenen:

1. Om de huidige url te bepalen
2. In de links die ik genereer zouden volgens mij alle queryparams moeten worden gezet die momenteel werden gezet. Als ik surf naar (imaginair pad) `/images?author=Wim`, dan verwacht ik dat de links in de response headers die `author=Wim` nog steeds bevatten. Anders gaat die paginering toch de mist in?

Backwards compatibility zal er dus niet zijn.

**Comment by koenedaele** [comment]
Als ik het goed begrijp is de library niet backwards compatible, en zou de volgende versie dan 1.0.0 of zo moeten zijn. Maar de REST api's gaan wel backwards compatible zijn, want er komt een header bij, maar er is niets dat wijzigt.

En inderdaad, de zoekparameters moeten mee doorgegeven worden in de Link header.

**Comment by Wim-De-Clercq** [comment]
Inderdaad, de backwards compatibility is enkel binnen de code zelf, niet voor iets dat de API aanroept.

**Comment by koenedaele** [comment]
Dan gewoon zorgen dat de semantic versioning correct staat. @claeyswo , akkoord?
