### ISSUE TITLE
Link header has wrong format

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/oe_utils#129]
The Link header generated in https://github.com/OnroerendErfgoed/oe_utils/commit/76c0827c3e489d3d52e242f52c9debb3d8debd1d#diff-031e08ece89f524681cc2ffc49ebdac4R146 is lacking a closing ">".

**Comment by koenedaele** [comment]
As reported in OnroerendErfgoed/beeldbank#838

**Comment by pythdasch** [comment]
https://github.com/OnroerendErfgoed/oe_utils/pull/131

**Comment by koenedaele** [comment]
Please add estimates to tickets before starting them.

**Comment by pythdasch** [comment]
@koenedaele I did it because it was just a typo. but yes, normally there has to be an estimate. sorry for this

**Comment by koenedaele** [comment]
Ok, please always add one. At the end of every sprint these estimates are used to track effort put into each application.
