### ISSUE TITLE
twine check

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/oe_utils#147]
Zie https://github.com/OnroerendErfgoed/scripts/issues/299

**Comment by axd1967** [comment]
twine check OK

**Comment by axd1967** [comment]
@kuylensa  

eigenaardig: we zitten op 1.3.3 op https://pypi.org/simple/oe-utils/ en 0.14  op http://vioe-pypi-prod-1.vm.cumuli.be/simple/oe-utils/.

**Comment by kuylensa** [comment]
dan zou ik op 't eerste zicht stellen dat `oe_utils` niet via http://vioe-pypi-prod-1.vm.cumuli.be opgevraagd wordt, maar rechtstreeks naar pypi.org.
Normaal wordt alles wat gevraagd wordt via interne pypi, maar niet gevonden op interne pypi, doorgestuurd naar pypi.org. Nedien ('s nachts) wordt via cron-job de access-logs doorlopen en binnengehaald op interne pypi.

Indien cronjob niet goed loopt, zouden we daar meer problemen mee moeten hebben, dat packages op interne niet de laatste versie hebben.
 
Maar zal 't proberen te controleren of speciefiek op die die `oe_utls` is of niet.

**Comment by kuylensa** [comment]
Crontab werkt alvast
```shell
root@vioe-pypi-prod-1:~# tail /var/log/cronjobs/pypi_cron.log
Tue Aug 13 05:30:04 CEST 2019 cron work
```

Oproepen `oe-utils` zonder versienummer geeft, dan wordt er gezien of `oe-utils` aanwezig is, wat zo is, met versie 0.14.
Oproepen `oe-utils==1.3.3` gaat enkel met een `--extra-index https://pypi.org/simple` omdat deze intern niet gevonden wordt, maar dan wel afgehaald wordt.
```shell
cronuser@vioe-pypi-prod-1:~$ tail -f /var/log/pypi/pypi.log
10.40.0.4 - - [13/Aug/2019 09:17:48] "GET /simple/oe-utils/ HTTP/1.1" 200 4500
```
Maar in die log staat niet bij welke versienummer er uiteindelijk bij pypi.org gehaald moet worden.
En als ik https://github.com/OnroerendErfgoed/scripts/blob/8f635860289341d840d12d8a297b28b911ce961b/servers/pypi/config/getpypip.py#L44 bezie, dan worden enkel 303's en 404's gevolgd om packages te gaan halen op pypi.org

**Comment by axd1967** [comment]
* pip haalt versies op volgens semver (bijvoorbeeld dev versies worden niet in aanmerking genomen tenzij expliciet vermeld).
* ik denk dat we oe-utils mogen wegsmijten op onze eigen pypi (http://vioe-pypi-prod-1.vm.cumuli.be/simple/oe-utils/) omdat https://pypi.org/simple/oe-utils/ die functie heeft overgenomen: @goessebr @Wim-De-Clercq ?

**Comment by Wim-De-Clercq** [comment]
Volgens mij mag dit ja, de enige reden om die nog te houden zou performance bij het downloaden zijn omdat onze server wrs dichter is dan de `pypi.org`.

**Comment by kuylensa** [comment]
Begint meer ticket voor interne pypi te worden.
Maar bedoeling van interne pypi is ook om als proxy te dienen, dat niet iedere keer naar internet gegaan moet worden...
`getpypip.py` is denk ik eerder voorzien om Apache-logs te verwerken. Ik weet niet of structuur van logs gewijzigd is sinds migratie van .mmis naar .cumuli 
https://github.com/OnroerendErfgoed/scripts/blob/8f635860289341d840d12d8a297b28b911ce961b/servers/pypi/config/getpypip.py#L68-L72

**Comment by axd1967** [comment]
die twine chck is ok, de pypi issues zijn interne zaken.
