### ISSUE TITLE
Beter exception handling voor beter debug

### ISSUE THREAD

**Issue by pythdasch** [OnroerendErfgoed/oe_utils#164]
https://github.com/OnroerendErfgoed/oe_utils/blob/ee1d6aa571efe2f3658ae91b12695701c01272ce/oe_utils/audit.py#L82

Het is gevaarlijk om niet de goeje exceptie te trackeeren. Beter is om één error te hebben en dan de juist exceptie te handling om goeje informatie aan te geven en ook om de app méer stabiel aan te doen.

de Exception class is niet één goeje manier om debugging. aan de plaats of except Exception as e wij moeten de juiste exceptie aan geven : 
except AttributeError as e

Multiple Exception is also possible : 
except IndexError:
except AttributeError.

als wij willen dat perfekt doen, kunnen wij ook de juiste error aan te géven voor iedere exceptie.

als deze applicatie is gebruik bij alle projekt is dat wel belangrijk.

**Comment by Wim-De-Clercq** [comment]
Het enige dat echt moet gebeuren is de 
```                    
log.error(e)
```
vervangen door
```
log.exception("error")
```

Hoe ga je anders bepalen welke exceptions dat we moeten catchen? Die code roept een random 'renderer' aan van het project dat deze decorator gebruikt. oe_utils kan nooit weten welke exceptions elke project mogelijks zal raisen.

**Comment by pythdasch** [comment]
de log.exception("error") is genoeg. het is waar dat elke exceptie kan tijd nemen.
