### ISSUE TITLE
debug range parser error

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/oe_utils#166]
add the content of the range header in the log output, so we know what is wrong

https://github.com/OnroerendErfgoed/oe_utils/blob/5f049247cccdccfb996c1673b111fc6711bcded2/oe_utils/range_parser.py#L84

in support of https://github.com/OnroerendErfgoed/inventaris/issues/2484

**Comment by cedrikv** [comment]
mee te nemen met volgende release (wel al fix gemerged in master)

**Comment by Wim-De-Clercq** [comment]
Commit op master blijft er gewoon in in nieuwe release, die code op zich is goed.
Het is gewoon wat gereformat bij #183 en test failure werd gefixt.
