### ISSUE TITLE
Review email

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#172]
### smtp.py
- [x] Verwijder pyramid dependency

De code in `smtp.py` heeft een dependency naar pyramid voor enkel deze method
```py
def text_(s, encoding='latin-1', errors='strict'):
    """ If ``s`` is an instance of ``binary_type``, return
    ``s.decode(encoding, errors)``, otherwise return ``s``"""
    if isinstance(s, binary_type):
        return s.decode(encoding, errors)
    return s
```
Die kunnen we evengoed zelf hier hebben staan.

- [x] onduidelijke param smtp
```py
    def __init__(self, smpt, sender):
        ''' smtp: Simple Mail Transfer Protocol (SMTP) to send mails
```
Hernoem `smtp` naar "host" of "smtp_host" en pas docstring aan. Zeg dat het de smtp server is.

- [x] verwijder property
Ik zie weinig nut in het gebruik van de property. Delete, verhuis dat naar gewoon veld in `__init__`. Eventueel bestaat die voor testen. Maar daar is waarschijnlijk wel een beter alternatief dan.

- [x] kleine code verbetering:
```py
        if message_html:
            part1 = MIMEText(message_plain, 'plain', _charset="UTF-8")
            part2 = MIMEText(message_html, 'html', _charset="UTF-8")

            # Attach parts into message container.
            # According to RFC 2046, the last part of a multipart message, in this case
            # the HTML message, is best and preferred.
            msg.attach(part1)
            msg.attach(part2)
        else:
            part1 = MIMEText(message_plain, 'plain', _charset="UTF-8")
            msg.attach(part1)
```
kan evengoed dit zijn:
```py
        plain_text = MIMEText(message_plain, 'plain', _charset="UTF-8")
        msg.attach(plain_text)
        if message_html:
            # According to RFC 2046, the last part of a multipart message, in this case
            # the HTML message, is best and preferred.
            html_text = MIMEText(message_html, 'html', _charset="UTF-8")
            msg.attach(html_text)
```
### __init__.py

- [x] get_oe_email_footer_plain footer plain

Er zitten heel veel [Enter]s in de plain footer. 
```py
print('------------')
print(get_oe_email_footer_plain())
print('------------')
```
```
------------

    

    Onroerend Erfgoed

    Herman Teirlinckgebouw  |  Havenlaan 88 bus 5  |  1000 Brussel

    www.onroerenderfgoed.be

    

    
------------
```
Ik denk dat alle `\n` in de code gewoon weg mag, omdat een [enter] binnen triple quoted strings sowieso al wordt behouden.

@goessebr zijn de hoeveelheid [enter]s de bedoeling?

**Comment by goessebr** [comment]
De \n mogen weg

Het verwachte resultaat is 
------------

    Onroerend Erfgoed
    Herman Teirlinckgebouw  |  Havenlaan 88 bus 5  |  1000 Brussel
    www.onroerenderfgoed.be

------------

**Comment by goessebr** [comment]
> De \n mogen weg
> 
> Het verwachte resultaat is
> 
> ```
> ------------
> 
>     Onroerend Erfgoed
>     Herman Teirlinckgebouw  |  Havenlaan 88 bus 5  |  1000 Brussel
>     www.onroerenderfgoed.be
> 
> ------------
> ```

**Comment by Wim-De-Clercq** [comment]
Extra change:
op deze lijn, bij het toevoegen van de files aan de mail
https://github.com/OnroerendErfgoed/oe_utils/blob/49e41cd014d6fcded5ecaaef5cd7405875beb26d/oe_utils/email/smtp.py#L66

Is het mogelijk om een string op te sturen. Als bijvoorbeeld de bijlage een csv, of txt file is.
Hierbij hebben we dan wel geen controle over de encoding van de string naar bytes.
Gevolg is dat als we vreemde characters in een csv hebben `ë©éàî`, dat het tricky wordt.
Bij lokale testen met python3 en het versturen van een csv met vreemde karakters komt er blijkbaar `cp-1252` encoding uit. 
De csv dan openen met bvb libreoffice calc of de meeste editors die by default UTF-8 gebruiken zorgt ervoor dat we de klassieke � hebben.

Dus:

TODO: if-statement toevoegen, kijken of de bijlage data een string is (eender wat niet-bytes) en een warning loggen dat de encoding mogelijks fout zal zijn.

Opgelet, strings in python 2 zijn bytes, strings in python3 zijn geen bytes.
De bovenstaande bug komt ook enkel voor bij python3.

Maar volgens mij is `if isinstance('x', bytes)` voldoende. Net omdat python2 strings wél ok zijn.
