### ISSUE TITLE
Remove deprecated OEInteger but change implementation

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#195]
We hebben die gedeprecate, maar gebruiken hem zelf wel nog in oe_utils.

**Comment by vancamti** [comment]
Zoals besproken op rocket chat kunnen we bij https://github.com/OnroerendErfgoed/oe_utils/blob/4692eb8e48b612f6d4eb14b77c325cb356ef29b8/oe_utils/validation/__init__.py#L89 geen instantie van de class `colander.Integer ` dus kunnen we die strict niet opleggen en blijft OEInteger toch noodzakelijk. Waarvan we dan wel implementatie wijzigen.
