### ISSUE TITLE
Generatie van feeds volledig herbekijken

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_utils#210]
Het is zo dat we momenteel binnen al onze toepassingen 1 monolithische feed hebben. Bij een aantal toepassingen begint het inladen van die feed ondertussen redelijk zwaar te worden. Het oorspronkelijke idee, ik weet niet meer waarom dat zo was, was om de feeds om de zoveel tijd te archiveren waarbij een deel op disk terechtkwam. Los van de problemen met backups is dit ook niet flexibel naar paginering toe. Eens een feed gearchiveerd zou zijn met bvb. 100 items per pagina is dit niet eenvoudig terug te draaien. De data zit momenteel steeds in 2 tabellen, feed, die enkel een getal bevat en feedentries die linken naar de feed. Als nu een bepaalde pagina van de feed wordt opgeladen gaat hij gewoon de feed ophalen en hier itereren over alle entries. Momenteel zit alles ook gewoon op 1 pagina, alle feeds hebben momenteel 1 entry in tabel feed.

Het idee zou zijn om die tabel feed te schrappen en bij de feedentries gewoon dynamisch een nummer opbouwen afhankelijk van een parameter uit de settings, feed_entries_per_page.

Er zijn mogelijk betere manieren maar onderstaande is een manier om dit te bereiken:

``` sql
select *, (row_number () over (order by id) -1) / feed_entries_per_page as "feed_id"
from feedentries order by id;
```

Todo:

#### https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/data/data_managers.py

- feed_mode en feed_repository weg
- get_from_archive, archive_feed en save_new_feed weg
- aanpassingen aan current_feed en get_sibling:
    current_feed wordt gewoon de max uit onderstaand voorbeeld, sibling kan berekend worden op basis van min/max, min heeft geen prev sibling, max geen next, alles tussenin gewoon +1/-1
``` sql
select max(feed_id), min(feed_id) from (
select (row_number () over (order by id) -1) / 10 as "feed_id"
from feedentries
) as "feed_ids"
```

#### https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/views/atom.py

- archive_current_feed en bijhorende functies weg
- get_atom_feed mag gewoon generate_atom_feed(feed_id) returnen
- overal wat aanpassingen nodig omdat feed geen model meer is maar enkel nog een id
- in elk project de generate_atom_feed nog aanpassen, en dan vooral het ophalen van de entries, tickets aan te maken in elk project apart

**Comment by claeyswo** [comment]
En tegelijk ook upgrade van feedgen libray want die geeft security warnings.

**Comment by koenedaele** [comment]
Het punt van een feed is normaal dat die opnieuw kan afgespeeld worden. Hoeveel entries daarbij juist in een bepaald stukje feed zitten is niet belangrijk, want er wordt met prev en next links gewerkt waarbij de grote van een bestand niet van tel is.

Dus, ik snap dat de feed te groot aan het worden is. Maar ik snap niet waarom we niet archiveren. Of wat dit voorstel dan wel juist doet, pagineren met welke API?

**Comment by claeyswo** [comment]
Hier splits je de feed gewoon in een willekeurig aantal pagina's, of eerder entries per pagina. En dan kan je inderdaad met de prev en next links naar de volgende/vorige. Functioneel verandert dit niets. En de code wordt er een pak duidelijker op.

Dat archiveren lijkt mij alleen maar voor problemen te zorgen. Dat moet om de x tijd gebeuren of hij blijft groeien, dat staat dan ergens op disk. Je zou het disk gedeelte kunnen laten vallen en dat archiveren uitvoeren dor gewoon feed_ids bij te maken en te herkoppelen maar ik zie de meerwaarde niet.
