### ISSUE TITLE
PDF wrapt de strings niet op de pagina.

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_utils#216]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/4599667/74947179-c9281c80-53fa-11ea-9fe8-063829a85a95.png">

Lange url valt er gewoon af

**Comment by claeyswo** [comment]
Als we dan toch nog iets moeten veranderen, misschien ook een parameter uri doorsturen, url in de qr code zelf is dan de endpoint om te kunnen opladen. Uri is dan http://id.erfgoed.net/resource/123
