### ISSUE TITLE
Minor bug in atomfeed view

### ISSUE THREAD

**Issue by vancamti** [OnroerendErfgoed/oe_utils#230]
Volgens mij zit er een kleine bug in (die in praktijk waarschijnlijk niet gaat voorkomen) https://github.com/OnroerendErfgoed/oe_utils/blob/d1035d1fc947f4c26596f60aa9624867bf80ba52/oe_utils/views/atom.py#L91 dit zou` if sibling is not None: ` moeten worden. Want als je nu een feed hebt met maar 2 pagina's zal de laatste pagina feed_id=1 hebben en die zijn previous sibling zal feed_id=0 hebben en dus zal die` If 0` evalueren naar `False` en de ref naar 'previous' wordt niet correct ingesteld. `If 0 is not None` zou wel het correcte resultaat geven.

**Comment by claeyswo** [comment]
Ja, dat gaat inderdaad problemen geven. Kunnen we niet gewoon bij die feed_id overal +1 doen? Dat hij start met 1 ipv 0, lijkt mij properder.

Zoiets dus:

select *, ((row_number () over (order by id) -1) / feed_entries_per_page) + 1 as "feed_id"
from feedentries order by id;

**Comment by vancamti** [comment]
Dat zou het probleem ook oplossen idd, dan zal die sibling in `if sibling` altijd minimaal 1 zijn en zal het correct evalueren.
