### ISSUE TITLE
Locatie component centraliseren

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_utils#28]
De (vernieuwde) locatie component in onze applicaties bevat heel wat wederkerende code. Het lijkt mij het beste om deze code te centraliseren en dan lijkt oe_utils de meest geschikte plaats. 

Deze component moet nog in tal van andere toepassingen aangepast worden, dus het leek mij een goed idee om hier niet te lang mee te wachten.

Concreet zijn volgende onderdelen herbruikbaar:

_Models_:
- LocatieElement
- Perceel
- OpenbaarDomein
- LocatieAdres

_Renderers_:
- locatie_element_adapter
- perceel_adapter
- openbaar_domein_adapter
- locatie_adres_adapter

_Validators_:
- LocatieElementen
- LocatieSchemaNode

_Restviews_:
- _verwerk_locatiedata

@BartSaelen, ik vernam dat jij zowat de beheerder bent van oe_utils. Wat is jouw mening over dit punt?

/cc @cahytinne @kmillet @koenedaele @claeyswo

**Comment by BartSaelen** [comment]
views zou ik sowieso niet naar oe_utils brengen, kan potentiel te veel verschillen.

Ik dacht dat ik de meeste validators al in oe_geoutils had zitten. Kan zijn dat ik er enkele vergeten ben. Dus die mag je daar onderbrengen.

Models, ja maar enkel als je kan zorgen dat ze op een of ander manier kunnen gekoppeld worden aan de declarative base van uw applicatie.

Renderers, ja maar enkel als het blijft werken met zowel de json renderer van Pyramid als met JSONPublish.

**Comment by BartSaelen** [comment]
+def _map_locatie(locatie_json, toelating): 
 +def _map_locatie_elementen(locatie_elementen_json): 

deze mappers kunnen misschien ook wel in een library

**Comment by BartSaelen** [comment]
Ik denk trouwens dat oe_geoutils een betere plek is voor locatie elementen dan oe_utils

**Comment by BartSaelen** [comment]
Die validators nog eens bekeken en die LocatieElementen validator is enkel van toepassing voor archeologie, dus niet geschikt voor in library

**Comment by goessebr** [comment]
> Die validators nog eens bekeken en die LocatieElementen validator is enkel van toepassing voor archeologie, dus niet geschikt voor in library

Het Archeologie project bevat nu toch al een 10tal deelprojecten dus dat is toch heel wat code die we dubbel hebben als we die validator niet centraliseren. Het blijft natuurlijk een afweging tussen dubbele code en de library niet onnodig groot maken. Ik wil jouw mening hier wel in volgen

**Comment by BartSaelen** [comment]
De afweging is voor mij eerder dat die validator dan verkeerd gebruikt kan worden in projecten die niet met 1 referentieadres werken maar met meerdere adrescomponenten. En ik denk dat er maar een 4-tal projecten zijn die deze validator gebruiken.

**Comment by goessebr** [comment]
Verplaatst naar oe_geoutils https://github.com/OnroerendErfgoed/oe_geoutils/issues/14
