### ISSUE TITLE
Fixen oude en recente testen na reactivatie van travis

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_utils#32]
Travis werd (opnieuw) opgezet. Het bleek dat verschillende van de testen niet succesvol waren in python 3

**Comment by goessebr** [comment]
https://github.com/OnroerendErfgoed/oe_utils/commit/42304ce0afd4a64acdddc57472dccbfdc3f59cb1
https://github.com/OnroerendErfgoed/oe_utils/commit/23315c1c913bcc6ff1fc699dc0e40c5c15a04806
https://github.com/OnroerendErfgoed/oe_utils/commit/e63409751b80612cd9cc0d9e9177565e4ddf84a6

**Comment by goessebr** [comment]
@BartSaelen @cahytinne @claeyswo , heeft iemand van jullie zin om wat test te corrigeren.

Lokaal werken de py.test testen. Travis is wat hardnekkiger: https://travis-ci.org/OnroerendErfgoed/oe_utils
Het zijn dingen die al langer in de code zitten maar met Travis opnieuw op te zetten zijn er wat issues boven gekomen

**Comment by BartSaelen** [comment]
fixed
