### ISSUE TITLE
Splitsen bij archiveren feed

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_utils#33]
Bedoeling zou zijn om bij het archiveren te kunnen splitsen over meerdere archives, bvb. er zijn 1400 entries, split staat op 500 dan zouden er 2 archives worden aangemaakt en blijft de current feed met 400 entries.

We hebben momenteel nog niets gearchiveerd en willen, zeker bij nota's gezien de aantallen, wel eens starten en dit zou een nice to have zijn. Als jullie echter denken dat dit bvb. 2 weken werk is laten we dat denk ik beter vallen.

**Comment by BartSaelen** [comment]
Ik denk dat we dit op een dag of 2 wel kunnen oplossen.

**Comment by BartSaelen** [comment]
Nog mee te nemen in deze sprint?

**Comment by claeyswo** [comment]
Als er nog ruimte is wel ja.

**Comment by BartSaelen** [comment]
oe_utils 0.14.0 is gereleased en bevat deze oplossing. Uit te rollen in projecten die dit nodig hebben.
