### ISSUE TITLE
Generieke indexer uit openbare onderzoeken halen en in OE_utils plaatsen

### ISSUE THREAD

**Issue by Pieter-Beckers** [OnroerendErfgoed/oe_utils#42]
De indexer die werd hergebruikt voor het indexeren na een commit werd in openbare onderzoeken generieker geschreven en zou in OE_utils kunnen komen (en uit openbare_onderzoeken gehaald worden).
De indexer is hier te vinden (nu ook met redis support):
https://github.com/OnroerendErfgoed/openbare_onderzoeken/blob/75d15a3b39bb1627f2944a345a5d5db5428593cb/openbare_onderzoeken/search/indexer.py

**Comment by Pieter-Beckers** [comment]
Nu ook met support voor redis:
https://github.com/OnroerendErfgoed/openbare_onderzoeken/blob/75d15a3b39bb1627f2944a345a5d5db5428593cb/openbare_onderzoeken/search/indexer.py

**Comment by BartSaelen** [comment]
https://github.com/OnroerendErfgoed/openbare_onderzoeken/blob/75d15a3b39bb1627f2944a345a5d5db5428593cb/openbare_onderzoeken/search/indexer.py#L101
voorzien dat er de naam van de queue kan meegegeven worden. Die delegate is een fully qualified method name en dus veel te lang en de deze zou in theorie ook niet altijd dezelfde hoeven zijn. Dus aparte parameters van maken, delegate en queue_name. Beter is hier ook een aparte methode van te maken in een aparte module over queue's. Dit kan nog op andere plaatsen dienen ook, buiten het zoeken en indexeren. Dus ook weg uit deze klasse. zie https://github.com/OnroerendErfgoed/oe_utils/issues/43

https://github.com/OnroerendErfgoed/openbare_onderzoeken/blob/75d15a3b39bb1627f2944a345a5d5db5428593cb/openbare_onderzoeken/search/indexer.py#L160
Aparte methode op module niveau van maken (zoals het was) gaat anders niet werken. Methoden hoeven niet per se in een klasse te zitten met Python. Hier zelfs beter niet, omdat die delegate dan gewoon kan verwijzen naar die methode.

**Comment by BartSaelen** [comment]
Ook nog ergens een prepare settings for index voorzien. Deze zorgt ervoor dat enkele settings die mee op de queue kunnen meegaan. Voorbeeld hieronder, kan waarschijnlijk ook wat generieker.

index_settings_keys = {'searchengine.baseurl', 'searchengine.index',
                       'oeauth.secret', 'oeauth.consumer_key', 'oeauth.consumer_secret', 'oeauth.callback_url',
                       'oeauth.authorize_url', 'oeauth.allow_roleless_users',
                       'oeauth.role_inheritor', 'oeauth.mock_user', 'oeauth.mock_user_userid',
                       'oeauth.mock_user_groups', 'oeauth.request_token_cookie_duration',
                       'sqlalchemy.url', 'oeauth.oauth_host', 'storageprovider.baseurl', 'storageprovider.collection',
                       'administratievegrenzen.url', 'redis.url', 'erfgoedgemeenten.oe_actor'}


def prepare_settings_for_index(settings):
    index_settings = {}
    for key in settings:
        if key in index_settings_keys or key.startswith('oeauth.cache'):
            index_settings[key] = settings[key]
    return index_settings

zie ook:
https://github.com/OnroerendErfgoed/adviezen/blob/master/adviezen/search/index.py#L44

https://github.com/OnroerendErfgoed/adviezen/blob/master/adviezen/search/index.py#L164

**Comment by Wim-De-Clercq** [comment]
Bestaat in https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/search/indexer.py
