### ISSUE TITLE
Audit probeert de Wijziging te bewaren, ook al komt er een exception bij het zetten van de resource_object_json

### ISSUE THREAD

**Issue by Pieter-Beckers** [OnroerendErfgoed/oe_utils#54]
Zie:
https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/audit.py#L63

De error wordt gelogd, maar het opslaan wordt nog steeds uitgevoerd, maar deze geeft een null constraint error (Nullable moet op False volgens https://doc.onroerenderfgoed.be/docs/authentiek_bron_pyramid/audit.html ).

Het opslaan zou eigenlijk niet mogen gebeuren in dit geval. 

Soms worden er wel lege resource_object_json gezet, dus nullable mag op True (documentatie aanpassen). Er wordt best naar de status code gekeken als de result een Response object is. Indien 2xx, mag deze wel doorkomen.

**Comment by claeyswo** [comment]
Nullable moet gewoon overal op true.
