### ISSUE TITLE
be able to build a search query string for elasticsearch

### ISSUE THREAD

**Issue by Pieter-Beckers** [OnroerendErfgoed/oe_utils#57]
As for now, queries are generated in separates projects. This could be a bit more generic.
Maybe we could even use a library for this. For example: https://elasticsearch-dsl.readthedocs.io/en/latest/

Necessary components:
query all, query string and sorting

**Comment by BartSaelen** [comment]
I suggest moving some of the duplicated code across projects to a more generic module in OE_Utils instead of using some other DSL. Our code already contains some specifics for the way we use ElasticSearch. Moving to something different should be combined with upgrading ElasticSearch.

**Comment by BartSaelen** [comment]
na implementatie door mij te reviewen
