### ISSUE TITLE
Review architecture of oe_utils?

### ISSUE THREAD

**Issue by Pieter-Beckers** [OnroerendErfgoed/oe_utils#64]
As the organization grows, there is more need of separate common libraries like oe_utils, but without additional requirements that oe_utils requires. You could pip install them with --no-deps flag, but a more proper way would be to split the libraries in different repos. Maybe we could have a pyramid_oe_utils for utils with pyramid integration.

This way, we could also integrate more generic things like capakey validation without worrying about the dependencies.

**Comment by Wim-De-Clercq** [comment]
I agree this should eventually be looked at. I remember writing scandaemon, and thought i'll use oe_utils, because i had to send an email, and oe_utils has a method for that. But installing pyramid for an application that doesn't need pyramid made me rethink that decision.

**Comment by Wim-De-Clercq** [comment]
Fixed in #185 due to the use of optional dependencies.
