### ISSUE TITLE
Generic Colander Validation

### ISSUE THREAD

**Issue by Pieter-Beckers** [OnroerendErfgoed/oe_utils#65]
There is a lot of code duplicity among different OE projects regarding validation. This could be moved to oe_utils, but for simplicity and separation of concerns, I suggest creating a different repository oe_validation. 
- This could contain request and response schema's needed for swagger documentation. See for example https://github.com/OnroerendErfgoed/beeldbank/blob/98b67a0617101ed4175e0faf6ac832838f257e22/beeldbankbeheer/beeldbankbeheer/validation/schemas.py#L9
- Different schema nodes for basic data types: https://github.com/OnroerendErfgoed/metaaldetectievondstmeldingen/blob/60298b892cc2341c78a2c27a9763cdf40be5dc6e/metaaldetectievondstmeldingen/validation/__init__.py#L11
-  Generic things like uri validators and sqlalchemy_validators: see for example: https://github.com/OnroerendErfgoed/premieaanvragen/blob/2b4ea4710d61c62f56d2f5feb3a4c0727f3b8696/premieaanvragen/validation/validators_ids.py#L24

**Comment by Wim-De-Clercq** [comment]
This is now placed in https://github.com/OnroerendErfgoed/oe_utils/tree/master/oe_utils/validation
I assume when the ticket was made this did not exist yet.
