### ISSUE TITLE
coverage van views en validation naar 100% brengen

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_utils#81]

**Comment by laevya** [comment]
@cahytinne 
Ik zit een beetje vast met de testen van de views. Als je tijd hebt, kan jij er dan eens even naar kijken en me misschien een beetje opweg zetten? 
Het gaat nog over deze lijnen code die getest moeten worden
- Lijn 24 en 25:
https://github.com/OnroerendErfgoed/oe_utils/blob/38b2dc56806ca32a176c3f36ac730e9c75fc4d8b/oe_utils/views/__init__.py#L19-L25
Hierbij weet ik niet hoe ik zorg voor een ValueError in mijn test. Ik heb al verschillende pogingen gedaan, maar zonder succes. (Bv gecommente test) https://github.com/OnroerendErfgoed/oe_utils/blob/eef95fe65aab71d0ee62eaf1864ee90e2f31d623/tests/test_views.py#L65-L73
- Volgende lijnen:
https://github.com/OnroerendErfgoed/oe_utils/blob/38b2dc56806ca32a176c3f36ac730e9c75fc4d8b/oe_utils/views/__init__.py#L52-L66
