### ISSUE TITLE
Rijksregister validatie klopt niet voor personen geboren begin 20ste eeuw

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_utils#82]
Ik heb hier een rijksregisternummer, 18120812401, van iemand geboren in 1918. In de validatiecode wordt ervan uitgegaan dat alles dat begin met 0 en 1 personen geboren zijn na 2000, waardoor er een 2 wordt voorgezet.

Hoe kunnen we weten of 18120812401 bvb. slaat op iemand geboren in 1918 of 2018?

Dit blokkeert momenteel sommige Magda calls.

@koenedaele

**Comment by koenedaele** [comment]
Goeie vraag. Ik ken niet veel van rijksregisternummers. Als ik wikipedia lees, dan kan je op basis van het controlegetal zien of er een 2 werd toegevoegd of niet?

> Een derde groep van twee cijfers is een controlegetal op basis van de 9 voorafgaande cijfers. Dat wordt berekend door het getal van negen cijfers, dat gevormd wordt door de aaneenschakeling van de geboortedatum en het reeksnummer, te delen door 97. De rest van deze deling ("modulo") wordt van 97 afgetrokken. Het aldus verkregen verschil is het controlenummer. Voor personen geboren in of na 2000 moet men een 2 voor het getal van negen cijfers zetten (+ 2000000000) alvorens te delen door 97

bv. 18120812401. 
 * Eerste  9 cijfers: 97 - MOD97(181208124) = 1 => geboren in 1918
 * Eerste 9 cijfers met extra2: 97 - MOD97(2181208124) = 30 => niet geboren in 2018; 18120812430 zou wel geboren zijn in 2018.

**Comment by claeyswo** [comment]
Dan passen we de test gewoon aan als volgt:

- check of de checksum klopt zonder iets aan te passen
- indien niet check of de checksum klopt door 2 te prependen

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/oe_utils/commit/21ec461c191106d1460d18121dc5a2b831baf976
