### ISSUE TITLE
Onnodige json view_config in exceptions.py

### ISSUE THREAD

**Issue by laevya** [OnroerendErfgoed/oe_utils#92]
De viewconfig voor json staat in de applicaties zelf (zie informatiecatalogus en inventaris). 
De view_config kan in oe_utils niet gebruikt worden, dus deze mogen weg.

**Comment by Wim-De-Clercq** [comment]
Ik vind ze eigenlijk wel handig dat ze hier staan en ik ze gewoon kan importeren om standaard responses te hebben bij errors.

Je moet gewoon bij het scannen een commit doen en dan kan je views zelf overriden ipv dubbele te maken
```
    config.scan('oe_utils.views')  # Get default error handler views
    config.commit()  # So we can override views previously created.
    config.scan('toelatingen_beschermd_erfgoed_aanvragen.views')
```

**Comment by goessebr** [comment]
Het probleem was dat we view_config decorator niet konden gebruiken. De view zelf moet sowieso blijven bestaan.
Als we de scan methode kunnen gebruiken om de view_config correct in de applicatie te krijgen dan denk ik dat we deze oe_utils views optimaal in de inventaris en de informatiecatalogus kunnen gebruiken en dat we daar de code kunnen verbeteren.

Op dit moment halen we de view op maar de view_config werd niet ingelezen dus we wrappen de view om er opnieuw decorators aan toe te kennen: https://github.com/OnroerendErfgoed/inventaris/blob/951275467e05eb0d48dae7d81f9aedeac8a53d6f/inventaris/views/exceptions.py#L24

Als ik het goed begrijp dan kunnen we net zo goed config.scan() gebruiken en dan is dat wrap gedoe helemaal niet nodig. Klopt dit?
In dat geval zal er wel nog een extra view_config decorator moeten worden toegevoegd aan https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/views/exceptions.py#L18 om de html exceptions ook op te vangen.

**Comment by Wim-De-Clercq** [comment]
> Als ik het goed begrijp dan kunnen we net zo goed config.scan() gebruiken en dan is dat wrap gedoe helemaal niet nodig. Klopt dit?
Inderdaad, de gewone `config.scan()` zal deze by default niet opnemen want  (uit documenatie)
```
        The ``package`` argument should be a Python :term:`package` or module
        object (or a :term:`dotted Python name` which refers to such a
        package or module).  If ``package`` is ``None``, the package of the
        *caller* is used.
```
Je bent dan wel verplicht om `config.commit()` te doen. Want anders zal pyramid crashen met de melding dat je duplicate views/routes hebt. Met de commit() erbij, gelden nieuwe views als overrides.

**Comment by goessebr** [comment]
@laevya kan jij hiervoor in de inventaris en de informatiecatalogus refactor issues aanmaken?

- de afhandeling van json exceptions mag via de generieke views van oe_utils. Zo worden eventuele algemene wijzigingen automatisch overgenomen.
- de afhandeling van html views mag via de wrapper blijven gebeuren. Anders gaan we er van uit dat  elke applicatie die dit gebruikt een error.jinja2 template heeft en dat willen we niet.

Dit issue mag je sluiten van zodra je de issues hebt aangemaakt in de applicaties. We laten de code hier ongemoeid Je leest best bovenstaande comments eens om alles te verduidelijken.
