### ISSUE TITLE
Testen toevoegen voor create_indexing_argument_parser

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_utils#96]
Tijdens de toevoeging van de functie create_indexing_argument_parser zijn er geen testen toegevoegd. Hierdoor is de testcoverage van deze library geen 100% meer: https://travis-ci.org/OnroerendErfgoed/oe_utils/jobs/421732815

Graag testen schrijven voor https://github.com/OnroerendErfgoed/oe_utils/blob/master/oe_utils/scripts/__init__.py#L5

Het test moet volgende parameters testen: offset limit index id

**Comment by ausy-ben** [comment]
Ik heb te veel moeilijkheden om de command line arguments te kunnen mocken, daarom is het beter dat Bram er eens naar kijkt.
